workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.seunome.sorteiofifa"
      node: 18.16.0
    scripts:
      - npm install -g @ionic/cli
      - npm cache clean --force
      - npm ci
      - npm run build
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
